export default {
  CHANGE_BUYER_DETAILS: `CHANGE_BUYER_DETAILS`,
  CREATE_ORDER: `CREATE_ORDER`,
  ADD_STYLE: `ADD_STYLE`,
  CHANGE_ORDER_DETAILS: `CHANGE_ORDER_DETAILS`,
  CHANGE_ORDER_SIZES: `CHANGE_ORDER_SIZES`
}